import tensorflow as tf
from tensorflow.python.ops import rnn_cell
from tensorflow.python.ops import seq2seq

import numpy as np

class GenModel():
    def __init__(self, args):
        self.args = args

        if args.gen_model == 'rnn':
            cell_fn = rnn_cell.BasicRNNCell
        elif args.gen_model == 'gru':
            cell_fn = rnn_cell.GRUCell
        elif args.gen_model == 'lstm':
            cell_fn = rnn_cell.BasicLSTMCell
        else:
            raise Exception("model type not supported: {}".format(args.model))

        with tf.variable_scope('GEN') as scope:
            cell = cell_fn(args.rnn_size)
            self.cell = cell = rnn_cell.MultiRNNCell([cell] * args.num_layers)
            # sequence of word tokens taken as input
            self.input_data = tf.placeholder(tf.int32, [args.batch_size, args.seq_length], name='input_data')

            self.latent_state = tf.placeholder(tf.float32, [args.batch_size, args.latent_size])

            # weights to map the latent state into the (usually) bigger initial state
            # right now this only works for rnn (other more complex models have more than
            # one initial state which needs to be given a value)
            # Right now we support up to two layers (state1 and state2)
            self.latent_to_initial_state1 = tf.Variable(tf.random_normal([args.latent_size, args.rnn_size], stddev=0.35, dtype=tf.float32), name='latent_to_intial_state1')
            self.latent_to_initial_state2 = tf.Variable(tf.random_normal([args.latent_size, args.rnn_size], stddev=0.35, dtype=tf.float32), name='latent_to_intial_state2')
            self.initial_state1 = tf.matmul(self.latent_state, self.latent_to_initial_state1)
            self.initial_state2 = tf.matmul(self.latent_state, self.latent_to_initial_state2)
            # these are the actual approximate word vectors generated by the model
            self.outputs = tf.placeholder(tf.float32, [args.seq_length, args.batch_size, args.rnn_size])
            self.lr = tf.Variable(0.0, trainable=False, name='learning_rate')
            self.has_init_seq2seq = False

    def attach_cost(self, disc_model):
        self.embedding = disc_model.embedding
        self.outputs = self.generate()
        self.loss = 1. - tf.reduce_mean(disc_model.discriminate_wv(self.outputs))
        tvars = tf.trainable_variables()
        grads, _ = tf.clip_by_global_norm(tf.gradients(self.loss, tvars),
                self.args.grad_clip)
        optimizer = tf.train.AdamOptimizer(self.lr)
        g_and_v = [(g, v) for g, v in zip(grads, tvars) if v.name.startswith('GEN') or v.name.startswith('embedding')]
        print '#########'
        for _, v in g_and_v:
            print v.name
        self.train_op = optimizer.apply_gradients(g_and_v)

    def generate(self):
        inputs = tf.split(1, self.args.seq_length, tf.nn.embedding_lookup(self.embedding, self.input_data))
        inputs = map(lambda i: tf.nn.l2_normalize(i, 1), [tf.squeeze(input_, [1]) for input_ in inputs])

        def loop(prev, i):
            return prev

        with tf.variable_scope('GEN', reuse=self.has_init_seq2seq) as scope:
            self.has_init_seq2seq = True
            if self.args.num_layers == 1:
                outputs, last_state = seq2seq.rnn_decoder(inputs, [self.initial_state1], self.cell, loop_function=loop, scope=scope)
            elif self.args.num_layers == 2:
                outputs, last_state = seq2seq.rnn_decoder(inputs, [self.initial_state1, self.initial_state2], self.cell, loop_function=loop, scope=scope)
            else:
                raise Exception('Unsupported number of layers. Use 1 or 2 layers for now..')
            outputs = map(lambda o: tf.nn.l2_normalize(o, 1), outputs)
        self.outputs = outputs
        return outputs
        

